@startuml
User -> System : Selected Cards
activate User
activate System
group Has Cards
System -> Database : Request Information
activate Database
Database --> System : Return Information
deactivate Database
System --> User : Display Cards
User -> System : Delete Card
System --> User : Remove Card
User -> System : Edit Card
System -> Database: Request Save
activate Database
Database --> System: Save Information
deactivate Database
end

group Has No Cards
System --> User : Display Add Cards
User -> System : Add Cards
System -> Database : Request Save
activate Database
Database --> System: Save Information
deactivate Database
end

group Go Through Test
loop Until Done
User -> System : Want Answer
System --> User : Show Answer
User -> System : Select Right or Wrong
System --> User : Update New Statistics
end
loop Until Done
User -> System : Retest Wrong
System --> System : Get Wrong Cards
System --> User: Display Wrong Cards
User -> System : Want Answer
System --> User : Show Answer
User -> System : Select Right or Wrong
System --> User : Update New Statistics
end
System -> Database : Request Save
activate Database
Database --> System: Save Information
deactivate Database
end

@enduml