@startuml
User -> System : Start Application
activate User
activate System
group Has Subjects
System -> Database : Request Information
activate Database
Database --> System : Return Information
deactivate Database
System --> User : Display Subjects
User -> System : Select Subject
end

group Has No Subjects
System --> User : Display Add Subject
loop Until Done
User -> System : Add Subject
System -> Database : Request Save
activate Database
Database --> System: Save Information
end
deactivate Database
end

@enduml