@startuml
User -> System : Selected Subject
activate User
activate System
group Has Sections
System -> Database : Request Information
activate Database
Database --> System : Return Information
deactivate Database
System --> User : Display Sections
User -> System : Select Sections
end

group Has No Sections
System --> User : Display Add Sections
loop Until Done
User -> System : Add Sections
System -> Database : Request Save
activate Database
Database --> System: Save Information
end
deactivate Database
end

@enduml