@startuml
User -> System : Selected Subject
activate User
activate System
group Has Sections
System -> Server : Request Information
activate Server
Server --> System : Return Information
deactivate Server
System --> User : Display Sections
User -> System : Select Sections
end

group Has No Sections
System --> User : Display Add Sections
User -> System : Add Sections
System -> Server : Request Save
activate Server
Server --> System: Save Information
deactivate Server
end

@enduml