@startuml

Class User
package System <<React>> {
Class Splash
Class HomePage
Class Create
Class Subject
Class Section
Class Notes
Class Test
}
Class Storage

User"1" -- "1"Splash : Open Up 
Splash"1" *-- "1"HomePage : Load
HomePage"1" o-- "1"Create : Select
HomePage"1" o-- "1"Test : Select
Create"1" *-- "1"Subject : Create
Subject"1" -- "*"Section : Create
Section"1" -- "*"Notes : Create
Subject"1" -- "1"Storage : Store

Test"1" -- "1"Storage : Pull




@enduml