@startuml
Actor User


User -> System : Turn on Application
Activate User
Activate System

System -> Server : Request User Information
Activate Server

Server --> System : Return User Information
Deactivate Server

System --> User : Display User Information

group Picking Test Option
User -> System : Pick Class
User -> System : Pick "Test Me"

System --> User : Display Section
User -> System : Pick Section

System -> System : Load Cards
System --> User : Start Test

loop Until Test Over
User -> System: : Answer Card
System --> User : Get New Card
System -> System : Keep Track of Stats
end

System --> User : Show Stats when done
System -> Server : Request to Save Stats
activate Server
Server --> System : Stats Saved for User
deactivate Server
User -> System : Select Homepage
end

group Adding New Class Option
User -> System : Selects Add New Class
User -> System : Enter Class Name
User -> System : Enter Section Information
System --> User : Display Section Page

loop Until All Cards Added
User -> System : Add New Card
System --> User : Show Blank Card
User -> System : Fill Out Information
User -> System : Save Card
System -> System : Store New Card
end

System -> Server : Request to Store Information
activate Server
Server --> System : Information Stored
deactivate Server
System --> User : Show Options
User -> System : Return Home
end

User -> System : Quit
System -> Server : Store New Information
activate Server
Server --> System : Information Updated
deactivate Server
System --> User : Shut Down
deactivate System
deactivate User
@enduml