@startuml

Class User
package ElStudioGato <<React>> {
Class Splash
Class Subjects
Class Section
Class FlashCards

Class AddToView
Class EditView
Class DeleteView
}
package Database <<React>> {
Class Storage
}

Subjects"1" --> "1"Storage : Saves To database on app close
Storage"1" <-- "1"Splash : Loads database on app open

User"1" -- "1"Splash : Open Up 

Splash"1" *-- "1"Subjects : Load
Subjects"1" -- "1"AddToView : contains

Subjects"1" -- "*"Section : Displays
Section"1" -- "1"AddToView : contains

Section"1" -- "*"FlashCards : Displays
FlashCards"1" -- "1"AddToView : contains
FlashCards"1" -- "1"EditView : contains
FlashCards"1" -- "1"DeleteView : contains


@enduml