@startuml
Actor User
Actor Storage

rectangle System {
User -- (Load Splash)
(Load Splash) .. (Show Subject) : <<Includes>>
(Show Subject) .. (Add Subject) : <<Includes>>
(Show Subject) .. (Delete Subject) :  <<Includes>>
(Show Subject) -- Storage
(Show Section) -- Storage
(Show Section) -- User
(Show Section) .. (Add Section) : <<Includes>>
(Show Section) .. (Delete Section) : <<Includes>>
(Show Cards) -- Storage
(Show Cards) -- User
(Show Cards) .. (Edit Cards) : <<Includes>>
(Show Cards) .. (Delete Cards) : <<Includes>>
(Show Cards) .. (Add Cards) : <<Includes>>
(Show Cards) .. (Show Answer) : <<Includes>>
(Show Answer) .. (Mark Wrong) : <<Includes>>
(Show Answer) .. (Mark Right) : <<Includes>>
(Mark Wrong) .. (Show Statics) : <<Includes>>
(Mark Right) .. (Show Statics) : <<Includes>>
(Mark Wrong) .. (Retest Wrong) : <<Includes>>
(Mark Right) .. (All Correct) : <<Includes>>
(Show Answer) .. (Retest All) : <<Includes>>
(All Correct) .. (Fling Cat) : <<Includes>>
(Show Statics) -- (Storage)
}



@enduml