@startuml
Actor user

Actor storage
rectangle System {
(load splash) ..> (show subject) : <<includes>>
(show subject) ...> (add) : <<includes>>
(show subject) ...> (delete) :  <<includes>>
(show subject) -- storage
(show subject) ...> (edit) : <<includes>>

(show section) -- storage
(show section) -- user
(show section) ..> (edit) : <<includes>>

(show flashcards) ..> (show question) : <<includes>>
(show section) ..> (add) : <<includes>>
(show section) ..> (delete) : <<includes>>
(show question) .. (show answer) : contains

(show flashcards) -- storage
(show flashcards) -- user
(show flashcards) ..> (edit) : <<includes>>
(show flashcards) ..> (delete) : <<includes>>
(show flashcards) ..> (add) : <<includes>>
(show flashcards) ..> (show answer) : <<includes>>

(show answer) ..> (mark wrong) : <<includes>>
(show answer) ..> (mark right) : <<includes>>
(mark wrong) ..> (show statics) : <<includes>>
(mark right) ..> (show statics) : <<includes>>

}



@enduml