@startsalt
{
{T
+ Load Splash
++  Goal
+++ Display the splash screen for the user.
++ Entry conditions
+++ The user has started the application.
++ Scenario
+++ The user has stated the application.
+++ The application pops up with the splash screen.
++ Exceptions
+++ None
++ Exit conditions
+++ Successful Exit Conditions
++++ List of Subjects appears.
+++ Failure Exit Conditions
++++ None
}
}
@endsalt