@startuml
title  elStudioGato Delete Cards


(*) --> "Student presses delete \non Flashcard Menu"
--> "System asks if you really want to delete"
if "Verified selection" then
     -->[yes]"Delete flashcard from list"
     --> ===done===
   else
     -->[no] ===done===
endif

--> "Display remaining cards"

@enduml